Implement examples hub
XRTK/Examples pull request #46
Opened 2021-08-15 16:21 UTC by FejZa

# XRTK - Mixed Reality Toolkit Pull Request

## Overview

Implement a simple `ExamplesHubSystem` that once registered with the root profile, will spawn a little UI with example selection. Examples can be configured via profiles. This is the beginning of efforts to create an XRTK examples hub application showcasing XRTK capabilities.

Depends on https://github.com/XRTK/XRTK-Core/pull/875

![examples-hands-profile](https://user-images.githubusercontent.com/9565734/129485199-d43bfc09-6f3e-442b-860d-d0326acdaa0f.PNG)
![examples-locomotion-profile](https://user-images.githubusercontent.com/9565734/129485200-e52ba9f1-d42a-453f-bab4-1b6d275b1400.PNG)
![examples-hub-system-profile](https://user-images.githubusercontent.com/9565734/129485203-753dfb6b-a165-4d08-81b6-15748c37530d.PNG)
![examples-hub-system](https://user-images.githubusercontent.com/9565734/129485204-2613d3f8-267d-487c-95f0-e1b12825be5e.PNG)
![examples-hub-ui](https://user-images.githubusercontent.com/9565734/129485205-a5534d00-fdc6-4e28-b5b4-3d8713fd7450.PNG)

2021-08-15 16:28 UTC, StephenHodgson commented on XRTK.Examples/Assets/XRTK.Examples/Editor/ExamplesHubSystemProfileInspector.cs
> +                selectedExampleData.ParentProfile = ThisProfile;
Is this the only place we use this?

2021-08-15 16:33 UTC, StephenHodgson commented on XRTK.Examples/Assets/XRTK.Examples/Editor/ExamplesHubSystemProfileInspector.cs
> +            var selectedExampleData = EditorGUI.ObjectField(rect, exampleDataProperty.objectReferenceValue, typeof(ExampleProfile), false) as ExampleProfile;
How come you couldn't use the default profile drawer?

2021-08-15 16:44 UTC, StephenHodgson requested changes
be sure to update the xrtk package reference once it get's published after the core PR is merged

2021-08-16 06:18 UTC, FejZa commented on XRTK.Examples/Assets/XRTK.Examples/Editor/ExamplesHubSystemProfileInspector.cs
> +            var selectedExampleData = EditorGUI.ObjectField(rect, exampleDataProperty.objectReferenceValue, typeof(ExampleProfile), false) as ExampleProfile;
![image](https://user-images.githubusercontent.com/9565734/129519364-fa377ecb-13f7-4deb-82ad-0d8786cafac1.png)
This is what I get with the default profile drawer. Unfortunately not working.

2021-08-16 06:23 UTC, FejZa commented
Update: I added a default ExamplesHubSystemProfile and made it part of the DemoMixedRealityRootProfile. That means loading hte base scene and pressing play, will spawn the Examples Hub UI by default.

Note: It is built in a way that it supports multi-scene editing in Unity. As soon as there is more than only the base scene loaded in Unity, the examples hub will not do anything and respect the developers scene setup. This is useful when you are working on a specific example and don't want to have to launch starting from the base scene every time.

2021-08-16 08:14 UTC, FejZa commented
@StephenHodgson there was no 0.2.19 released for Core it seems. We have to merge to the main branch I guess?

2021-08-16 11:02 UTC, StephenHodgson commented
@FejZa it's the 0.3.0-preview

2021-08-16 11:03 UTC, StephenHodgson commented on XRTK.Examples/Assets/XRTK.Examples/Editor/ExamplesHubSystemProfileInspector.cs
> +            var selectedExampleData = EditorGUI.ObjectField(rect, exampleDataProperty.objectReferenceValue, typeof(ExampleProfile), false) as ExampleProfile;
I'll take a look and see if I can get this sorted out

2021-08-25 04:37 UTC, StephenHodgson commented
/azp run

2021-09-04 17:29 UTC, StephenHodgson commented
@FejZa I merged in the locomotion PR then updated this one, but I'd like to you confirm that this is updated correctly

2021-09-04 17:59 UTC, FejZa commented
I pulled this out of the locomotion system PR. Since that one is merged this is obsolete. But I'll double-check.

2021-09-04 22:16 UTC, closed without merging